### ISSUE TITLE
Example Overpass Query

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#11]
/*
This is an example Overpass query.
Try it out by pressing the Run button above!
You can find more examples with the Load tool.
_/
way
  [railway=subway]({{bbox}});
/_added by auto repair_/
(._;>;);
/_end of auto repair*/
out;

**Comment by stevevance** [comment]
Something got messed up when copying and pasting this (either from the website to the text file, or the text file to the Github issue box). I'm fixing it...

```
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“railway=subway”
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “railway=subway”
  node["railway"="subway"]({{bbox}});
  way["railway"="subway"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

**Comment by yfreemark** [comment]
This is the site:
http://overpass-turbo.eu

Key for railways:
http://wiki.openstreetmap.org/wiki/Key:railway

Exact correct query attached
<img width="157" alt="screen shot 2015-12-24 at 11 37 21" src="https://cloud.githubusercontent.com/assets/8240806/11996880/be8b9ef8-aa32-11e5-8416-37f266366371.png">
