### ISSUE TITLE
Add stop data for mexico, canada, and figure out what stops are missing!

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#12]

**Comment by yfreemark** [comment]
This is partially resolved. No good data available for Edmonton or Calgary. Need commuter rail stops for Vancouver, Montreal, and Toronto

**Comment by stevevance** [comment]
Are those cities available via OpenStreetMap?

**Comment by yfreemark** [comment]
Yes, but it doesn't come out cleanly. Not a top priority, but I'll get to it when I can!

**Comment by stevevance** [comment]
Can this be closed?

**Comment by yfreemark** [comment]
Sure. There are some incremental changes I will make to the geojsons in the coming days but I have them marked elsewhere so go ahead and close this.
