### ISSUE TITLE
BRT color switcher doesn't work for under construction

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#14]
The item in lines 218-226 in app.js that controls the color of the BRT lines does seem to work for the proposed and funded projects, but it doesn't work for the under construction projects. Any idea why?

**Comment by yfreemark** [comment]
A related issue: Is it possible to style existing commuter rail separately from existing other stuff? Can you write that somewhere in the app.js where it switches status? lines 269-300.

**Comment by stevevance** [comment]
If there's a property (a column) in the GeoJSON, then you can use that to style the feature. 
Notice this code at 259:

```
switch(p.Mode) {
                case "Bus Rapid Transit":
                    style.color = "#b2182b";
                break;

                default:
                    style.color = "#2166ac";
                break;  
            }
```

**Comment by yfreemark** [comment]
No I saw that but what was weird was that it wasn't working for the under construction projects only. 

Can you pick a property (like BRT) AND a specific Json (like existing lines) SIMULTANEOUSLY?

**Comment by yfreemark** [comment]
OK! This minor problem has been solved (an issue of field names!).

But, if you know how to pick a property AND a specific JSON simultaneously, that would be helpful!

**Comment by stevevance** [comment]
I'm not really sure where you're at in this, but you can see inside the `onEachFeature()` function that there are two `switch()` statements, controlled by the `mode` feature property and the status attribute (defined when you process layers). 

A switch might not be the most efficient way to do this unless you use a complex hierarchy in a single switch with sub-switch statements, or if you're careful that the color definition in one switch doesn't overwrite the color definition in the first switch.

**Comment by yfreemark** [comment]
OK, I figured this out. Thanks!
