### ISSUE TITLE
adding zoom:to buttons on key

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#16]
for example, if you clicked on seattle or LA on the key, could it zoom in to those cities?

**Comment by yfreemark** [comment]
I put this on the key. It would be awesome if it could be one of those click and select things with multiple options that would reposition the map.

**Comment by stevevance** [comment]
What are the coordinates you want each city to zoom to? 

Create an object in the `app.js` like this:

```
var cities = {
    "losangeles": {
        "lat": 30.9,
       "lng": -122
    },
    "seattle": {
        "lat": 44.3,
       "lng": -122
    },
}
```

That way you can easily write a function called like so `zoomToCity("losangeles");`

**Comment by yfreemark** [comment]
OK! I added these cities! I also added a drop-down menu where I would like this to happen.

Now, I don't know how to do this "easy" function that actually makes the zoom happen... :)
