### ISSUE TITLE
still kind of slow

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#17]
So, while I do think the website is faster than before, it is still slow. For some reason, you can't drag the map when you've first loaded the screen until you've zoomed in and/or out. Any sense of why this would be?

**Comment by stevevance** [comment]
That doesn't happen for me. Can you make a screencast? (Use QuickTime Player or CloudApp.)

**Comment by yfreemark** [comment]
see google drive.

**Comment by stevevance** [comment]
I made some changes that affect the user experience, but I think I got rid of the "stuck" problem.
