### ISSUE TITLE
send email form

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#18]
i added a form using basic HTML to allow people to send comments about mistakes to the left side key of the site.

In theory, instead of it opening peoples' email apps and forcing them to send the comment, it would send an email automatically to me. I know this requires using PHP, but i don't know how to install this function, exactly. Do you have a sense?

**Comment by stevevance** [comment]
Use an embedded form from [Wufoo](http://wufoo.com). So much easier.

**Comment by yfreemark** [comment]
I'll use that for now, but Wufoo kind of sucks because the free plan only gives 100 responses a month and it won't even let you redirect back to your site....

**Comment by stevevance** [comment]
Jotform is a competitor, but I don't know if they do better on those features.

**Comment by stevevance** [comment]
I see that you added it. Questions:
1. Why do you require email? Is this necessary to accept a map suggestion?
2. Do you want the suggestion box to be bigger?

**Comment by yfreemark** [comment]
Email not required. I clarified that. I don't care about the size of the box. It is for select users!
