### ISSUE TITLE
adding existing lines and stations

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#2]
YF is about done with this

**Comment by stevevance** [comment]
@yfreemark Thanks for editing the GeoJSON file to truncate the digits.

**Comment by yfreemark** [comment]
I'm having a projection problem: The shape file I have for existing transit is set at NAD 83. This appears to “show” the situation correctly, but when I save as a GeoJSON in WGS 84, you get the situation you see on the west coast, namely lines significantly to the east of where they’re supposed to be. Any ideas on what I’m doing wrong here?

**Comment by yfreemark** [comment]
Projection problem solved. Now here is where I'll list things that eventually need to be fixed about the existing transit map:
- Need to add San Juan Tren Urbano
- Maybe add Santo Domingo Metro and anything in Cuba?
- Could also add Panama City Metro and anything else in Latin America

**Comment by yfreemark** [comment]
- Need to add Chicago Loop Link
- New York SBS
- Miami busways
- LA busways
- Bakersfield BRT
- Seattle RapidRide (but maybe not) + Swift
- Vancouver commuter train
- Toronto commuter train
- Montreal commuter train
- Ottawa busway
- Ottawa O Train

**Comment by stevevance** [comment]
When you're done extracting all of the data you need from OpenStreetMap, I think it would be a good idea to provide a file for others to download with these transit lines (in one file if they can be easily separated out), and a [link to the tutorial I wrote](http://www.stevencanplan.com/2015/12/how-to-extract-highways-and-subway-lines-from-openstreetmap-as-a-shapefile/).

**Comment by yfreemark** [comment]
Yep, will do!
