### ISSUE TITLE
Convert all <font> tags to proper HTML elements with style classes

### ISSUE THREAD

**Issue by stevevance** [stevevance/ttp-2016-transit-investments#20]
`<font>` is an outmoded HTML tag. 
These should be converted to the appropriate `<p>, <span>, <div>` positioning elements, and then given `style="className"` attributes.

**Comment by yfreemark** [comment]
OK, this is done!

**Comment by stevevance** [comment]
Thank you. 

At a future time we'll convert tables to `<div>`
