### ISSUE TITLE
Where should the default center be?

### ISSUE THREAD

**Issue by stevevance** [stevevance/ttp-2016-transit-investments#21]
Think of how a user arrives to our map of lots of transit projects in North America. 

Are they interested in browsing the continent to see what's going on everywhere, or do you think they're interested in a specific location?

I think that people are interested in a specific location and they're either going to click one of your "key cities" or they are going to search for it, or double click many-many times to zoom into it. 

Therefore I suggest we have one or all of the following:
-Making the Search control work
-Loading the map on a random "key city" - this is a good idea because it helps your map tell a story. 
-Using GPS to locate the user to their city (although this is probably a bad idea because there's a high chance there's no construction in their city)

**Comment by yfreemark** [comment]
OK, I agree with you. I actually think that starting in Chicago is good (it seems appropriate on several levels--it is non-coastal; it is easily recognizable; it is where we are based; it has projects), but can you make it so it loads the lines when it initially gets there? When I first open the page, it loads Chicago correctly, but doesn't load the lines even though we're at the zoom level to theoretically make that happen. You have to zoom in and out to see the lines.

In addition, can we have a popup say "Chicago" and below that say something like "drag the map or use the menu on the left to explore North America."

I am going to add more metros to the list.

I need help making the searching work! But I'm not going to be able to get that going tonight!

**Comment by stevevance** [comment]
Will make these changes about showing the lines in Chicago/encouraging the user to go other places. 

Search: use another issue to talk about this.

**Comment by stevevance** [comment]
Fixed in commit https://github.com/stevevance/ttp-2016-transit-investments/commit/c1822251e87ebb9f5c80545e77d899affe4636a9
