### ISSUE TITLE
Change how the cities[] array is organized

### ISSUE THREAD

**Issue by stevevance** [stevevance/ttp-2016-transit-investments#22]
I changed how the array of cities and their "zoom to" coordinates is formatted. 

Can you reorganize your bigger array of cities (which I've renamed to `citiesNew`) to match my `cities` array?

It essentially needs to look like this:

```
cities = [
                    {
                        "name": "Los Angeles",
                        "lat": 34,
                        "lng": -118
                    },
```

Once you're done, rename the `citiesNew` variable to `cities` and delete the older, smaller `cities` variable.

**Comment by yfreemark** [comment]
OK, this is excellent!. I fixed it, I believe.

**Comment by stevevance** [comment]
It looks like you manually put them in alphabetical order. In the future, when you want to add more cities, I can make it so the array is sorted automatically before it's displayed in the `<select>` dropdown menu.
