### ISSUE TITLE
Blurry-looking text on the "More info" dialog

### ISSUE THREAD

**Issue by stevevance** [stevevance/ttp-2016-transit-investments#23]
![screenshot 2016-01-02 22 44 55](https://cloud.githubusercontent.com/assets/1330459/12077297/d21fe5a6-b1a2-11e5-83dd-9663894e3cc4.png)

The text on the "More information about this page" dialog appears blurry. The above screenshot shows it compared to the permanent text on the page. I think this has to do with either the font choice and styling (size, weight, etc.) or with the animation of the dialog. 

I'll try and rule out animation right now.

**Comment by stevevance** [comment]
I'm pretty sure the `fadeIn` animation isn't the problem.

**Comment by yfreemark** [comment]
Weird, I'm not getting that? Look

<img width="1267" alt="screen shot 2016-01-03 at 4 27 07" src="https://cloud.githubusercontent.com/assets/8240806/12078319/43bab9c8-b1d2-11e5-9687-a5815f93f9ed.png">

**Comment by stevevance** [comment]
Which monitor I view it on affects this. The screenshot was taken on my non-retina monitor. This isn't really important, and I may try a fix later, so leave the issue open.
