### ISSUE TITLE
Mobile view looks bad

### ISSUE THREAD

**Issue by stevevance** [stevevance/ttp-2016-transit-investments#27]
<img width="363" alt="screenshot 2016-01-03 12 49 43" src="https://cloud.githubusercontent.com/assets/1330459/12080184/80493360-b218-11e5-9ed2-b842f6c8b048.png">
When you view the site on mobile, it will look like the above. 
What we can do is detect if the user is on mobile and hide the left-side key. Then, to open the left-side key, the user could tap the logo (or a new button).

**Comment by yfreemark** [comment]
Yes that's a great idea. Actually we probably want to keep the zoom to region thing always be there so is it possible to have a separate div that only shows up on mobile?

**Comment by stevevance** [comment]
Yes. Go ahead and create the <div> the way you want it to appear on mobile and I'll write the code that displays it for mobile users.

**Comment by yfreemark** [comment]
Can you put in a empty space for it with a new div class name, like "mobilekey"? I can get to it in about four hours.

**Comment by stevevance** [comment]
@yfreemark yeah, it's called `<div class="mobile-key"></div>`

**Comment by stevevance** [comment]
fixed
