### ISSUE TITLE
Add a layer on-off clicker to key

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#37]
Allow users to be able to click an individual layer on an off using a checkbox on the key.

When clicked, the new layer should load, as well as Skobbler's night map as a background.

**Comment by stevevance** [comment]
In the chooser, do you want all layers listed, or do you want specific layers listed?

**Comment by yfreemark** [comment]
Just one layer. This would be a "special" layer--all the others should stay on at all times.

**Comment by yfreemark** [comment]
To clarify, what I'm looking for is the following:
1. Below "Switch base map" in the key, there should be a click box that, by default, is not clicked. Next to the box, it should say "Special layer" (provisionally).
2. When the user clicks that box, the base map should automatically switch to the Skobbler night map. The night map should not be available in the switch base map drop down. In addition, a geojson layer "Special_layer.geojson" (provisional title) should load onto the map.
3. When the user unclicks the box, the night map and special layer should disappear and the base map should return to the default Streets layer.

**Comment by stevevance** [comment]
Is the special layer data already uploaded?
I would like a map layer to test this on, one that's not already in use. 

Do you want the existing lines to stay when the special layer is shown?

**Comment by stevevance** [comment]
This is nearly done. 

Add a new layer to the `layers` object in `index.html` and give it an extra property of `"special": true`. Then, that layer, and any other layers without the `special` property, or that have `"special": false` will not show unless you click the checkbox on the map legend.

**Comment by stevevance** [comment]
@yfreemark check it out now!
