### ISSUE TITLE
Create a style for stations

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#38]
I want to add in some stations data: Would it be possible to create a style for a new stations layer that would be not a place mark but a little dot with a black outline and a white inside? Or perhaps the style of the dot would be alterable based on the mode, as with the lines currently?

**Comment by stevevance** [comment]
Let's set some base assumptions first:
- All point data are markers. 
- All markers, to be displayed, require icons. 
- Icons can be images, or they can be CSS

Here's how to [establish a CSS icon](http://leafletjs.com/reference.html#icon):

```
var myIcon = L.divIcon({className: 'my-div-icon'});
// you can set .my-div-icon styles in CSS
```

Then, when you want the marker to use this icon, you set it the same way you would an icon that is an image:

```
L.marker([50.505, 30.57], {icon: myIcon}).addTo(map);
```

**Comment by stevevance** [comment]
Some of them seem centered, but others don't. [Here's the full docs on making a CSS icon](http://leafletjs.com/reference.html#icon) where you might see something about centering it. It says 

```
The icon will be aligned so that this point is at the marker's geographical location. 
Centered by default if size is specified, also can be set in CSS with negative margins.
```
