### ISSUE TITLE
styling

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#4]
Can I style the pop ups (in other words, text, color, etc.)? Where do I do that?

Can I style the key on the right? Where do I do that?

How do you format the place marks?

**Comment by yfreemark** [comment]
For the place marks, for the existing stops, I want small black circles. For the renovating ones, larger but not too large orange rectangles.

**Comment by stevevance** [comment]
_Popups_
You can style these with standard HTML where it says `content` in `function onEachFeature()`. 

_Key_
There's no way to style the key, because it's a simple layer chooser. You can design your own key as a "control" box that gets positioned in one of the 4 corners, or you can [find a plugin](http://leafletjs.com/plugins.html) that helps you insert "control" boxes. 

_Markers_
The best bet is probably to [install AwesomeMarkers](https://github.com/lvoogdt/Leaflet.awesome-markers). This is what I use on Chicago Cityscape and you basically tell the plugin the name of the icon/symbol you want, and the color, and it creates the marker.

**Comment by yfreemark** [comment]
Markers: I don't know how to tell the plugin which things I want it to mark.
- I put it in the app.js file [line 48], but nothing seems to be happening. Problem is on line 50, I think, where I don't know how to replace the coordinates with just the stations. is there any way to do that? But I'm not sure it's working at all, because there's supposed to be an icon on Rotterdam, but nothing is showing up.
- I supposedly installed all of the necessary background things in the index.html lines 56-62.

Popups: Very helpful.
Two things:
1. There's a big gap between the title and the content. Any idea how to make that smaller?
2. Is it possible to have the website link always show up at the bottom? Or should I just reformat the file so that website is always last? That might be easiest.

Key:
I'll get to later!

**Comment by yfreemark** [comment]
Key:

I have decided I don't want the control bar at all, other than switching between base maps (which we can leave in the existing style). I just want a key on the left side. I have removed the clickers on the right side. I don't want users to be able to click on and off layers.

**Comment by stevevance** [comment]
_Markers_
I'll take a look at installing AwesomeMarkers. 

_Popups_
1. Point to the code that controls this; if you can't find the line, then find it in the inspector and take a screenshot. 
2. It's simple to make it appear last. 

_Key_
You don't want which control bar at all?
Be more specific: there's the layer chooser, which switches between Streets, Building Name, and Satellite, and then there's the "legend" that you want that comes as a Leaflet "control" box.

**Comment by yfreemark** [comment]
Popups:
- Gap between title and content: not a big deal. The inspector won't let me find it? confusingly? It's just like in the leaflet map container? But it's okay really because it looks fine.
- I redid the layers so website is last, so this is no longer a worry.

Key
- I want the layer chooser! So I left that there. (Just don't want the legend.) The one thing is I want to change the font to Archivo Narriow as with the remainder of the key text, and I think this is controlled in the leaflet stored CSS? Like, I don't think I control that on our side? Oh, actually, if it IS possible, it would be AMAZING if we could incorporate the layer chooser into the left side key.... but I understand if that's too complicated :)

Markers
Looks good.

**Comment by stevevance** [comment]
_Popups_
I think the gap problem in the popups might be due to your (liberal) use of the `<font>` tag in the site. This is an outdated way to style text; use CSS to control line heights, text size, and the like.

_Key_
Which text is using Archivo Narrow and which is not?

**Comment by yfreemark** [comment]
Yeah I might change the text tags later but not a rush. Spacing problem has nothing to do with the text tags, but I agree that I can style using css. Currently popups are using Open Sans and key is using Archivo Narrow. I think it would make sense for the later switched to also use Archivo.
