### ISSUE TITLE
get rid of lat longs in station data

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#8]
Prior to exporting as GeoJSON, remove the latitude and longitude columns from the data. This data will be added automatically upon exporting as GeoJSON.

**Comment by yfreemark** [comment]
This is done.

**Comment by stevevance** [comment]
Did you commit it to the repo?
When you make commit comments, you can close the issue from the comment by typing "removed lat/lng data from stations, resolves issue #8" and then Github will automatically close the issue and link that issue to the commit.
